# Server Configuration
server.port=${SERVER_PORT:3000}

# Zoom Configuration
zoom.client.id=${ZOOM_CLIENT_ID:tqAlbjparEB1Rjhb1kvjuuWDOG2VSjJ8Fnx3}
zoom.client.secret=${ZOOM_CLIENT_SECRET:ldVZXX6uABvt0zezngGDt0sqJYBBHHttnJgX}
zoom.secret.token=${ZOOM_SECRET_TOKEN:4U6zsFM9TPOQDnuAE0zB7A}

# Application Configuration
app.mode=webhook
app.webhook.path=/webhook

# Logging
logging.level.com.zoom=DEBUG
logging.level.org.springframework.web.socket=WARN
